# Generated by Django 5.1.7 on 2025-03-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('members', models.ManyToManyField(related_name='clubs', to='home.person')),
            ],
        ),
    ]
